import type { Locale } from "./content";

export const techniqueMedia = [
  { key: "rig", number: "A", src: "/real-trip/rig-hands-closeup.webp" },
  { key: "helm", number: "B", src: "/real-trip/helm-from-behind.webp" },
  { key: "meal", number: "C", src: "/real-trip/food-aboard-closeup.webp" },
] as const;

export const approvedGalleryMedia = [
  { key: "veronika", number: "12", src: "/real-trip/group-veronika-clear.webp" },
  { key: "groupSea", number: "13", src: "/real-trip/group-trip-dimitris-visible.webp" },
  { key: "guestCatch", number: "14", src: "/real-trip/guest-catch-private.webp" },
  { key: "guestTrophy", number: "15", src: "/real-trip/guest-trophy-fish.webp" },
  { key: "guestFishing", number: "16", src: "/real-trip/guest-fishing.webp" },
  { key: "underway", number: "17", src: "/real-trip/boat-at-sea-private.webp" },
  { key: "youngAngler", number: "18", src: "/real-trip/young-angler-private.webp" },
  { key: "rigTogether", number: "19", src: "/real-trip/rig-preparation-private.webp" },
  { key: "barbecue", number: "20", src: "/real-trip/barbecue-meal-private.webp" },
  { key: "groupCatch", number: "21", src: "/real-trip/group-catch-private.webp" },
  { key: "largeCatch", number: "22", src: "/real-trip/young-guest-large-catch-private.webp" },
  { key: "dimitrisFish", number: "23", src: "/real-trip/dimitris-large-fish.webp" },
  { key: "mealAboard", number: "24", src: "/real-trip/meal-on-board-private.webp" },
  { key: "womanFishing", number: "25", src: "/real-trip/woman-fishing-face-blurred.webp" },
  { key: "trophy", number: "26", src: "/real-trip/dimitris-trophy-catch.webp" },
  { key: "soup", number: "27", src: "/real-trip/fresh-fish-soup.webp" },
  // Sent by Dimitris on 5 August 2026. He and his partner appear unmasked with
  // their consent; the guest and the child in the background do not.
  // frame: "high" keeps the subject in view — these are tall portraits whose
  // subject sits near the top, and the square gallery crop would cut it off.
  { key: "dimitrisBonito", number: "28", src: "/real-trip/dimitris-bonito.webp", frame: "high" },
  { key: "crewBonito", number: "29", src: "/real-trip/crew-bonito.webp" },
  { key: "crewGurnard", number: "30", src: "/real-trip/crew-gurnard.webp" },
  { key: "crewOctopus", number: "31", src: "/real-trip/crew-octopus.webp" },
  { key: "guestPandora", number: "32", src: "/real-trip/guest-pandora.webp" },
  { key: "catchPandora", number: "33", src: "/real-trip/catch-pandora.webp", frame: "high" },
  { key: "catchGurnard", number: "34", src: "/real-trip/catch-gurnard-deck.webp" },
  { key: "catchBucket", number: "35", src: "/real-trip/catch-bucket.webp" },
  { key: "boatPuppy", number: "36", src: "/real-trip/boat-puppy.webp" },
  // Sent by Dimitris on 8-9 August 2026. He, his partner Victoria and their
  // son appear unmasked — he confirmed all three. Every other guest and every
  // guest's child is masked. deckAfternoon carries five masks, guestFamily and
  // guestsEvening four each; the rest had no identifiable face to begin with.
  { key: "dimitrisNight", number: "37", src: "/real-trip/dimitris-night-pandora.webp", frame: "high" },
  { key: "sonNight", number: "38", src: "/real-trip/son-night-pandora.webp", frame: "high" },
  { key: "familySwim", number: "39", src: "/real-trip/family-swim-stop.webp" },
  { key: "barbecuePlatter", number: "40", src: "/real-trip/barbecue-platter.webp" },
  { key: "kelyfosCoast", number: "41", src: "/real-trip/kelyfos-coast.webp" },
  { key: "coveSwimmers", number: "42", src: "/real-trip/cove-swimmers.webp" },
  { key: "deckAfternoon", number: "43", src: "/real-trip/deck-afternoon.webp" },
  { key: "coveWide", number: "44", src: "/real-trip/cove-wide.webp" },
  { key: "kelyfosTurquoise", number: "45", src: "/real-trip/kelyfos-turquoise.webp" },
  { key: "guestFamilyRods", number: "46", src: "/real-trip/guest-family-rods.webp" },
  { key: "guestsEveningRods", number: "47", src: "/real-trip/guests-evening-rods.webp" },
] as const;

type TechniqueKey = (typeof techniqueMedia)[number]["key"];
type GalleryKey = (typeof approvedGalleryMedia)[number]["key"];
type MediaText = { alt: string; caption: string };

type GalleryContent = {
  techniqueTitle: string;
  techniqueItems: Record<TechniqueKey, MediaText>;
  eyebrow: string;
  title: string;
  intro: string;
  privacyNote: string;
  items: Record<GalleryKey, MediaText>;
};

export const approvedGalleryContent: Record<Locale, GalleryContent> = {
  en: {
    techniqueTitle: "See the setup, the helm and the meal",
    techniqueItems: {
      rig: { alt: "Hands preparing the simple single-hook bottom fishing rig", caption: "The simple rig prepared on board" },
      helm: { alt: "A guest learning at the boat helm, photographed from behind", caption: "Learning at the helm" },
      meal: { alt: "A close view of food served aboard Fishing 4 You", caption: "A real meal served aboard" },
    },
    eyebrow: "Real moments · Privacy respected",
    title: "Catches, company and life aboard.",
    intro: "A genuine look at fishing days with Dimitris: preparing the tackle, sharing a catch and enjoying food by the Aegean.",
    privacyNote: "Faces are blurred where requested. Only approved photographs are shown.",
    items: {
      veronika: { alt: "Veronika with friends beside the catch on the boat", caption: "A shared catch with Veronika" },
      groupSea: { alt: "A group enjoying a fishing day at sea with faces privacy-protected", caption: "A group day at sea" },
      guestCatch: { alt: "A guest holding a fish aboard with the face privacy-protected", caption: "A guest's catch" },
      guestTrophy: { alt: "An adult guest holding a large fish aboard Fishing 4 You", caption: "A proud catch aboard" },
      guestFishing: { alt: "An adult guest fishing from the boat under a bright Aegean sky", caption: "Waiting for the next pull" },
      underway: { alt: "Fishing 4 You travelling across the Aegean", caption: "Fishing 4 You underway" },
      youngAngler: { alt: "A young angler fishing aboard with the face privacy-protected", caption: "A young angler's moment" },
      rigTogether: { alt: "Dimitris helping prepare fishing tackle aboard", caption: "Preparing the rig together" },
      barbecue: { alt: "Friends sharing a barbecue meal aboard with faces privacy-protected", caption: "Lunch beside the Aegean" },
      groupCatch: { alt: "A group gathered around the day's catch with children privacy-protected", caption: "A catch shared at the marina" },
      largeCatch: { alt: "A young guest with a large fish and face privacy-protected", caption: "A memorable large catch" },
      mealAboard: { alt: "A meal shared on board with guests' faces privacy-protected", caption: "A meal on board" },
      womanFishing: { alt: "An adult guest holding a fishing rod aboard with her face privacy-protected", caption: "Fishing along the coast" },
      dimitrisFish: { alt: "Dimitris holding a large fish aboard", caption: "Dimitris and a large fish" },
      trophy: { alt: "Dimitris presenting a trophy fish", caption: "A trophy catch with Dimitris" },
      soup: { alt: "Fresh fish soup cooking in a pot aboard", caption: "Fresh fish soup prepared aboard" },
      dimitrisBonito: { alt: "Dimitris holding a bonito caught on a lure, rod still in hand", caption: "Dimitris with a bonito" },
      crewBonito: { alt: "A crew member holding up a bonito under the boat awning", caption: "A bonito taken on the troll" },
      crewGurnard: { alt: "Dimitris and a crew member holding a tub gurnard with its blue fins spread", caption: "A tub gurnard, fins open" },
      crewOctopus: { alt: "A crew member holding an octopus at the quay, with one of the boat dogs beside her", caption: "Octopus brought in at the quay" },
      guestPandora: { alt: "A guest holding a pandora aboard with the face privacy-protected, Dimitris behind him", caption: "A guest's pandora" },
      catchPandora: { alt: "A red pandora held up over the rail, with a child in the background privacy-protected", caption: "A red pandora over the rail" },
      catchGurnard: { alt: "A tub gurnard on the deck matting with its blue pectoral fin spread", caption: "The blue fin of a tub gurnard" },
      catchBucket: { alt: "A bucket of bogue, picarel and a pandora kept fresh in seawater", caption: "The bucket after a morning" },
      boatPuppy: { alt: "A young cream dog sitting on the blue bow of the boat in the marina", caption: "The youngest of the crew" },
      dimitrisNight: { alt: "Dimitris holding a pandora he has just landed during a night trip", caption: "A pandora on the night trip" },
      sonNight: { alt: "Dimitris' son holding a pandora caught on a night trip", caption: "His son's catch after dark" },
      familySwim: { alt: "Victoria and her son resting on the rocks at a swimming stop", caption: "A swimming stop along the coast" },
      barbecuePlatter: { alt: "A platter of grilled prawns, fried fish and Greek salad served on the boat", caption: "The barbecue served on board" },
      kelyfosCoast: { alt: "The rocky coastline of Kelyfos island seen from the water", caption: "Kelyfos island" },
      coveSwimmers: { alt: "Two swimmers in the clear water of a quiet cove below the cliffs", caption: "Swimming in a quiet cove" },
      deckAfternoon: { alt: "Guests resting on the shaded deck between stops, faces privacy-protected", caption: "The afternoon on deck" },
      coveWide: { alt: "A wide view of the cove with swimmers and the pine-covered cliff above", caption: "The cove from the boat" },
      kelyfosTurquoise: { alt: "Clear turquoise water over rocks beside the cliffs of Kelyfos", caption: "Turquoise water at Kelyfos" },
      guestFamilyRods: { alt: "A family fishing from the rail at sunset, faces privacy-protected", caption: "A family at the rail" },
      guestsEveningRods: { alt: "Guests fishing in the evening light with the coast behind, faces privacy-protected", caption: "Evening lines in the water" },
    },
  },
  el: {
    techniqueTitle: "Δείτε την αρματωσιά, το τιμόνι και το γεύμα",
    techniqueItems: {
      rig: { alt: "Χέρια που ετοιμάζουν την απλή αρματωσιά βυθού με ένα αγκίστρι", caption: "Η απλή αρματωσιά που ετοιμάζεται στο σκάφος" },
      helm: { alt: "Επισκέπτης μαθαίνει στο τιμόνι του σκάφους, φωτογραφημένος από πίσω", caption: "Μαθαίνοντας στο τιμόνι" },
      meal: { alt: "Κοντινή εικόνα φαγητού που σερβίρεται στο Fishing 4 You", caption: "Ένα αληθινό γεύμα στο σκάφος" },
    },
    eyebrow: "Αληθινές στιγμές · Σεβασμός στην ιδιωτικότητα",
    title: "Ψαριές, παρέα και ζωή στο σκάφος.",
    intro: "Μια αυθεντική ματιά στις ημέρες ψαρέματος με τον Δημήτρη: προετοιμασία εξοπλισμού, κοινές ψαριές και φαγητό δίπλα στο Αιγαίο.",
    privacyNote: "Τα πρόσωπα έχουν θολωθεί όπου ζητήθηκε. Εμφανίζονται μόνο εγκεκριμένες φωτογραφίες.",
    items: {
      veronika: { alt: "Η Βερόνικα με φίλους δίπλα στην ψαριά στο σκάφος", caption: "Μια κοινή ψαριά με τη Βερόνικα" },
      groupSea: { alt: "Παρέα σε ημέρα ψαρέματος με προστατευμένα πρόσωπα", caption: "Μια ομαδική ημέρα στη θάλασσα" },
      guestCatch: { alt: "Επισκέπτης κρατά ψάρι στο σκάφος με προστατευμένο πρόσωπο", caption: "Η ψαριά ενός επισκέπτη" },
      guestTrophy: { alt: "Ενήλικος επισκέπτης κρατά ένα μεγάλο ψάρι στο Fishing 4 You", caption: "Μια περήφανη ψαριά στο σκάφος" },
      guestFishing: { alt: "Ενήλικος επισκέπτης ψαρεύει από το σκάφος κάτω από τον φωτεινό ουρανό του Αιγαίου", caption: "Περιμένοντας το επόμενο τράβηγμα" },
      underway: { alt: "Το Fishing 4 You ταξιδεύει στο Αιγαίο", caption: "Το Fishing 4 You εν πλω" },
      youngAngler: { alt: "Νεαρός ψαράς στο σκάφος με προστατευμένο πρόσωπο", caption: "Η στιγμή ενός νεαρού ψαρά" },
      rigTogether: { alt: "Ο Δημήτρης βοηθά στην προετοιμασία της αρματωσιάς", caption: "Ετοιμάζοντας μαζί την αρματωσιά" },
      barbecue: { alt: "Φίλοι μοιράζονται μπάρμπεκιου στο σκάφος με προστατευμένα πρόσωπα", caption: "Γεύμα δίπλα στο Αιγαίο" },
      groupCatch: { alt: "Παρέα γύρω από την ψαριά με προστατευμένα τα πρόσωπα των παιδιών", caption: "Μια κοινή ψαριά στη μαρίνα" },
      largeCatch: { alt: "Νεαρός επισκέπτης με μεγάλο ψάρι και προστατευμένο πρόσωπο", caption: "Μια αξέχαστη μεγάλη ψαριά" },
      mealAboard: { alt: "Γεύμα στο σκάφος με προστατευμένα τα πρόσωπα των επισκεπτών", caption: "Γεύμα στο σκάφος" },
      womanFishing: { alt: "Ενήλικη επισκέπτρια κρατά καλάμι στο σκάφος με προστατευμένο πρόσωπο", caption: "Ψάρεμα κατά μήκος της ακτής" },
      dimitrisFish: { alt: "Ο Δημήτρης κρατά ένα μεγάλο ψάρι στο σκάφος", caption: "Ο Δημήτρης με ένα μεγάλο ψάρι" },
      trophy: { alt: "Ο Δημήτρης παρουσιάζει ένα μεγάλο ψάρι", caption: "Μια σπουδαία ψαριά με τον Δημήτρη" },
      soup: { alt: "Φρέσκια ψαρόσουπα μαγειρεύεται σε κατσαρόλα στο σκάφος", caption: "Φρέσκια ψαρόσουπα στο σκάφος" },
      dimitrisBonito: { alt: "Ο Δημήτρης κρατά παλαμίδα πιασμένη με τεχνητό δόλωμα, με το καλάμι στο άλλο χέρι", caption: "Ο Δημήτρης με μια παλαμίδα" },
      crewBonito: { alt: "Μέλος του πληρώματος κρατά ψηλά μια παλαμίδα κάτω από την τέντα του σκάφους", caption: "Παλαμίδα στο συρτό" },
      crewGurnard: { alt: "Ο Δημήτρης και μέλος του πληρώματος κρατούν καπόνι με ανοιγμένα τα γαλάζια πτερύγια", caption: "Καπόνι με ανοιχτά πτερύγια" },
      crewOctopus: { alt: "Μέλος του πληρώματος κρατά χταπόδι στην προκυμαία, με έναν από τους σκύλους του σκάφους δίπλα", caption: "Χταπόδι στην προκυμαία" },
      guestPandora: { alt: "Επισκέπτης κρατά λυθρίνι στο σκάφος με προστατευμένο πρόσωπο, ο Δημήτρης πίσω του", caption: "Το λυθρίνι ενός επισκέπτη" },
      catchPandora: { alt: "Κόκκινο λυθρίνι υψωμένο πάνω από την κουπαστή, με παιδί στο βάθος με προστατευμένο πρόσωπο", caption: "Κόκκινο λυθρίνι στην κουπαστή" },
      catchGurnard: { alt: "Καπόνι στο κατάστρωμα με ανοιγμένο το γαλάζιο θωρακικό πτερύγιο", caption: "Το γαλάζιο πτερύγιο του καπονιού" },
      catchBucket: { alt: "Κουβάς με γόπες, μαρίδες και ένα λυθρίνι διατηρημένα σε θαλασσινό νερό", caption: "Ο κουβάς μετά από ένα πρωινό" },
      boatPuppy: { alt: "Νεαρός ανοιχτόχρωμος σκύλος κάθεται στην μπλε πλώρη του σκάφους στη μαρίνα", caption: "Ο νεότερος του πληρώματος" },
      dimitrisNight: { alt: "Ο Δημήτρης κρατά ένα λυθρίνι που μόλις έπιασε σε νυχτερινή έξοδο", caption: "Λυθρίνι στη νυχτερινή έξοδο" },
      sonNight: { alt: "Ο γιος του Δημήτρη κρατά ένα λυθρίνι από νυχτερινό ψάρεμα", caption: "Η ψαριά του γιου του μετά το σκοτάδι" },
      familySwim: { alt: "Η Βικτώρια και ο γιος της ξεκουράζονται στα βράχια σε στάση για μπάνιο", caption: "Στάση για μπάνιο στην ακτή" },
      barbecuePlatter: { alt: "Πιατέλα με ψητές γαρίδες, τηγανητά ψάρια και χωριάτικη σαλάτα στο σκάφος", caption: "Το μπάρμπεκιου στο σκάφος" },
      kelyfosCoast: { alt: "Η βραχώδης ακτή του νησιού Κελυφος από τη θάλασσα", caption: "Το νησί Κελυφος" },
      coveSwimmers: { alt: "Δύο κολυμβητές στα καθαρά νερά ενός ήσυχου όρμου κάτω από τους βράχους", caption: "Κολύμπι σε ήσυχο όρμο" },
      deckAfternoon: { alt: "Επισκέπτες ξεκουράζονται στο σκιερό κατάστρωμα, με τα πρόσωπα προστατευμένα", caption: "Το απόγευμα στο κατάστρωμα" },
      coveWide: { alt: "Πανοραμική άποψη του όρμου με κολυμβητές και τον πευκόφυτο βράχο", caption: "Ο όρμος από το σκάφος" },
      kelyfosTurquoise: { alt: "Καθαρά τυρκουάζ νερά πάνω από βράχια δίπλα στους γκρεμούς του Κελυφους", caption: "Τυρκουάζ νερά στο Κελυφος" },
      guestFamilyRods: { alt: "Οικογένεια ψαρεύει από την κουπαστή στο ηλιοβασίλεμα, με τα πρόσωπα προστατευμένα", caption: "Μια οικογένεια στην κουπαστή" },
      guestsEveningRods: { alt: "Επισκέπτες ψαρεύουν στο απογευματινό φως με την ακτή πίσω, με τα πρόσωπα προστατευμένα", caption: "Απογευματινές πετονιές στο νερό" },
    },
  },
  ro: {
    techniqueTitle: "Vezi montura, cârma și masa",
    techniqueItems: {
      rig: { alt: "Mâini care pregătesc montura simplă de fund cu un singur cârlig", caption: "Montura simplă pregătită la bord" },
      helm: { alt: "Un oaspete învață la cârma bărcii, fotografiat din spate", caption: "Învățând la cârmă" },
      meal: { alt: "Prim-plan cu mâncarea servită la bordul Fishing 4 You", caption: "O masă adevărată servită la bord" },
    },
    eyebrow: "Momente reale · Intimitate respectată",
    title: "Capturi, prieteni și viață la bord.",
    intro: "O privire autentică asupra zilelor de pescuit cu Dimitris: pregătirea echipamentului, bucuria capturii și masa lângă Marea Egee.",
    privacyNote: "Fețele sunt blurate acolo unde s-a cerut. Sunt afișate doar fotografii aprobate.",
    items: {
      veronika: { alt: "Veronika alături de prieteni și captura de pe barcă", caption: "O captură împărțită cu Veronika" },
      groupSea: { alt: "Un grup într-o zi de pescuit pe mare, cu fețele protejate", caption: "O zi pe mare cu prietenii" },
      guestCatch: { alt: "Un oaspete ține un pește la bord, cu fața protejată", caption: "Captura unui oaspete" },
      guestTrophy: { alt: "Un oaspete adult ține un pește mare la bordul Fishing 4 You", caption: "O captură impresionantă la bord" },
      guestFishing: { alt: "Un oaspete adult pescuiește de pe barcă sub cerul luminos al Mării Egee", caption: "Așteptând următoarea trăsătură" },
      underway: { alt: "Fishing 4 You navigând pe Marea Egee", caption: "Fishing 4 You în larg" },
      youngAngler: { alt: "Un pescar tânăr la bord, cu fața protejată", caption: "Momentul unui pescar tânăr" },
      rigTogether: { alt: "Dimitris ajută la pregătirea monturii de pescuit", caption: "Pregătind montura împreună" },
      barbecue: { alt: "Prieteni la o masă cu grătar pe barcă, cu fețele protejate", caption: "Prânz lângă Marea Egee" },
      groupCatch: { alt: "Un grup în jurul capturii zilei, cu fețele copiilor protejate", caption: "O captură împărțită în port" },
      largeCatch: { alt: "Un oaspete tânăr cu un pește mare și fața protejată", caption: "O captură mare, de neuitat" },
      mealAboard: { alt: "O masă la bord, cu fețele oaspeților protejate", caption: "O masă la bord" },
      womanFishing: { alt: "O oaspete adultă ține lanseta la bord, cu fața protejată", caption: "Pescuit de-a lungul coastei" },
      dimitrisFish: { alt: "Dimitris ține un pește mare la bord", caption: "Dimitris și un pește mare" },
      trophy: { alt: "Dimitris prezintă un pește impresionant", caption: "O captură de trofeu cu Dimitris" },
      soup: { alt: "Supă proaspătă de pește pregătită într-o oală la bord", caption: "Supă proaspătă de pește la bord" },
      dimitrisBonito: { alt: "Dimitris ține o pălămidă prinsă la vobler, cu lanseta în cealaltă mână", caption: "Dimitris cu o pălămidă" },
      crewBonito: { alt: "Un membru al echipajului ridică o pălămidă sub copertina bărcii", caption: "Pălămidă prinsă la trolling" },
      crewGurnard: { alt: "Dimitris și un membru al echipajului țin o rândunică de mare cu aripioarele albastre desfăcute", caption: "Rândunică de mare, cu aripile deschise" },
      crewOctopus: { alt: "Un membru al echipajului ține o caracatiță pe cheu, cu unul dintre câinii bărcii alături", caption: "Caracatiță adusă la cheu" },
      guestPandora: { alt: "Un oaspete ține un pagel la bord, cu fața protejată, Dimitris în spatele lui", caption: "Pagelul unui oaspete" },
      catchPandora: { alt: "Un pagel roșu ridicat deasupra balustradei, cu un copil în fundal, cu fața protejată", caption: "Un pagel roșu la balustradă" },
      catchGurnard: { alt: "Rândunică de mare pe covorul punții, cu aripioara pectorală albastră desfăcută", caption: "Aripa albastră a rândunicii de mare" },
      catchBucket: { alt: "O găleată cu boghe, smarizi și un pagel ținute proaspete în apă de mare", caption: "Găleata după o dimineață" },
      boatPuppy: { alt: "Un cățel crem stând pe prova albastră a bărcii, în port", caption: "Cel mai tânăr din echipaj" },
      dimitrisNight: { alt: "Dimitris ține un pagel prins chiar atunci, în ieșirea de noapte", caption: "Un pagel în ieșirea de noapte" },
      sonNight: { alt: "Fiul lui Dimitris ține un pagel prins la pescuitul de noapte", caption: "Captura fiului său, după lăsarea nopții" },
      familySwim: { alt: "Victoria și fiul ei se odihnesc pe stânci într-o oprire pentru baie", caption: "O oprire pentru baie pe coastă" },
      barbecuePlatter: { alt: "Platou cu creveți la grătar, pește prăjit și salată grecească, servit pe barcă", caption: "Grătarul servit la bord" },
      kelyfosCoast: { alt: "Coasta stâncoasă a insulei Kelyfos, văzută de pe apă", caption: "Insula Kelyfos" },
      coveSwimmers: { alt: "Doi înotători în apa limpede a unui golf liniștit, sub stânci", caption: "Baie într-un golf liniștit" },
      deckAfternoon: { alt: "Oaspeți odihnindu-se pe puntea umbrită între opriri, cu fețele protejate", caption: "După-amiaza pe punte" },
      coveWide: { alt: "Priveliște largă a golfului, cu înotători și stânca acoperită de pini deasupra", caption: "Golful văzut de pe barcă" },
      kelyfosTurquoise: { alt: "Apă turcoaz limpede peste stânci, lângă falezele Kelyfos", caption: "Apa turcoaz de la Kelyfos" },
      guestFamilyRods: { alt: "O familie pescuind de la balustradă la apus, cu fețele protejate", caption: "O familie la balustradă" },
      guestsEveningRods: { alt: "Oaspeți pescuind în lumina serii, cu coasta în spate, cu fețele protejate", caption: "Fire în apă, seara" },
    },
  },
  ru: {
    techniqueTitle: "Посмотрите на снасть, штурвал и обед",
    techniqueItems: {
      rig: { alt: "Руки готовят простую донную снасть с одним крючком", caption: "Простая снасть, подготовленная на борту" },
      helm: { alt: "Гость учится управлять лодкой, вид со спины", caption: "Знакомство со штурвалом" },
      meal: { alt: "Еда, поданная на борту Fishing 4 You, крупным планом", caption: "Настоящий обед на борту" },
    },
    eyebrow: "Настоящие моменты · Уважение к приватности",
    title: "Улов, компания и жизнь на борту.",
    intro: "Настоящие рыболовные дни с Димитрисом: подготовка снастей, радость от улова и еда у Эгейского моря.",
    privacyNote: "Лица размыты там, где это было необходимо. Показаны только одобренные фотографии.",
    items: {
      veronika: { alt: "Вероника с друзьями и уловом на лодке", caption: "Общий улов с Вероникой" },
      groupSea: { alt: "Группа на морской рыбалке с защищёнными лицами", caption: "День в море с друзьями" },
      guestCatch: { alt: "Гость держит рыбу на борту, лицо защищено", caption: "Улов гостя" },
      guestTrophy: { alt: "Взрослый гость держит крупную рыбу на борту Fishing 4 You", caption: "Впечатляющий улов на борту" },
      guestFishing: { alt: "Взрослый гость рыбачит с лодки под ярким небом Эгейского моря", caption: "В ожидании следующей поклёвки" },
      underway: { alt: "Fishing 4 You идёт по Эгейскому морю", caption: "Fishing 4 You в море" },
      youngAngler: { alt: "Юный рыбак на борту, лицо защищено", caption: "Момент юного рыбака" },
      rigTogether: { alt: "Димитрис помогает подготовить рыболовную снасть", caption: "Готовим снасть вместе" },
      barbecue: { alt: "Друзья за обедом с барбекю на лодке, лица защищены", caption: "Обед у Эгейского моря" },
      groupCatch: { alt: "Группа рядом с дневным уловом, лица детей защищены", caption: "Общий улов в марине" },
      largeCatch: { alt: "Юный гость с крупной рыбой, лицо защищено", caption: "Запоминающийся крупный улов" },
      mealAboard: { alt: "Обед на борту, лица гостей защищены", caption: "Обед на борту" },
      womanFishing: { alt: "Взрослая гостья держит удочку на борту, лицо защищено", caption: "Рыбалка вдоль побережья" },
      dimitrisFish: { alt: "Димитрис держит крупную рыбу на борту", caption: "Димитрис и крупная рыба" },
      trophy: { alt: "Димитрис показывает трофейную рыбу", caption: "Трофейный улов с Димитрисом" },
      soup: { alt: "Свежий рыбный суп готовится в кастрюле на борту", caption: "Свежий рыбный суп на борту" },
      dimitrisBonito: { alt: "Димитрис держит пеламиду, пойманную на воблер, удочка в другой руке", caption: "Димитрис с пеламидой" },
      crewBonito: { alt: "Член команды поднимает пеламиду под тентом лодки", caption: "Пеламида, взятая на троллинге" },
      crewGurnard: { alt: "Димитрис и член команды держат морского петуха с расправленными голубыми плавниками", caption: "Морской петух с раскрытыми плавниками" },
      crewOctopus: { alt: "Член команды держит осьминога на причале, рядом одна из лодочных собак", caption: "Осьминог на причале" },
      guestPandora: { alt: "Гость держит пагелла на борту, лицо защищено, позади него Димитрис", caption: "Пагелл гостя" },
      catchPandora: { alt: "Красный пагелл поднят над леером, на заднем плане ребёнок с защищённым лицом", caption: "Красный пагелл у леера" },
      catchGurnard: { alt: "Морской петух на палубном коврике с расправленным голубым грудным плавником", caption: "Голубой плавник морского петуха" },
      catchBucket: { alt: "Ведро с бопсом, смаридой и пагеллом, сохранёнными в морской воде", caption: "Ведро после утренней рыбалки" },
      boatPuppy: { alt: "Молодой светлый пёс сидит на синем носу лодки в марине", caption: "Самый младший в команде" },
      dimitrisNight: { alt: "Димитрис держит пагра, только что пойманного на ночной рыбалке", caption: "Пагр на ночной рыбалке" },
      sonNight: { alt: "Сын Димитриса держит пагра, пойманного ночью", caption: "Улов его сына после заката" },
      familySwim: { alt: "Виктория с сыном отдыхают на скалах во время остановки для купания", caption: "Остановка для купания у берега" },
      barbecuePlatter: { alt: "Блюдо с креветками на гриле, жареной рыбой и греческим салатом на лодке", caption: "Барбекю на борту" },
      kelyfosCoast: { alt: "Скалистый берег острова Келифос со стороны моря", caption: "Остров Келифос" },
      coveSwimmers: { alt: "Двое пловцов в прозрачной воде тихой бухты под скалами", caption: "Купание в тихой бухте" },
      deckAfternoon: { alt: "Гости отдыхают на затенённой палубе между остановками, лица скрыты", caption: "День на палубе" },
      coveWide: { alt: "Широкий вид бухты с пловцами и поросшей соснами скалой", caption: "Бухта с лодки" },
      kelyfosTurquoise: { alt: "Прозрачная бирюзовая вода над камнями у скал Келифоса", caption: "Бирюзовая вода у Келифоса" },
      guestFamilyRods: { alt: "Семья ловит рыбу у борта на закате, лица скрыты", caption: "Семья у борта" },
      guestsEveningRods: { alt: "Гости ловят рыбу в вечернем свете, берег позади, лица скрыты", caption: "Вечерние снасти в воде" },
    },
  },
  de: {
    techniqueTitle: "Montage, Steuerstand und Mahlzeit ansehen",
    techniqueItems: {
      rig: { alt: "Hände bereiten die einfache Grundmontage mit einem Haken vor", caption: "Die einfache Montage an Bord" },
      helm: { alt: "Ein Gast lernt am Steuerstand, von hinten fotografiert", caption: "Einblick am Steuerstand" },
      meal: { alt: "Nahaufnahme des Essens an Bord von Fishing 4 You", caption: "Eine echte Mahlzeit an Bord" },
    },
    eyebrow: "Echte Momente · Privatsphäre respektiert",
    title: "Fänge, Gemeinschaft und Leben an Bord.",
    intro: "Ein authentischer Einblick in Angeltage mit Dimitris: Ausrüstung vorbereiten, Fänge teilen und Essen an der Ägäis genießen.",
    privacyNote: "Gesichter wurden auf Wunsch unkenntlich gemacht. Gezeigt werden nur freigegebene Fotos.",
    items: {
      veronika: { alt: "Veronika mit Freunden und dem Fang auf dem Boot", caption: "Ein gemeinsamer Fang mit Veronika" },
      groupSea: { alt: "Eine Gruppe beim Angeltag auf See mit geschützten Gesichtern", caption: "Ein gemeinsamer Tag auf See" },
      guestCatch: { alt: "Ein Gast hält einen Fisch an Bord, das Gesicht ist geschützt", caption: "Der Fang eines Gastes" },
      guestTrophy: { alt: "Ein erwachsener Gast hält einen großen Fisch an Bord von Fishing 4 You", caption: "Ein stolzer Fang an Bord" },
      guestFishing: { alt: "Ein erwachsener Gast angelt unter dem hellen Himmel der Ägäis vom Boot aus", caption: "Warten auf den nächsten Biss" },
      underway: { alt: "Fishing 4 You unterwegs auf der Ägäis", caption: "Fishing 4 You auf See" },
      youngAngler: { alt: "Ein junger Angler an Bord mit geschütztem Gesicht", caption: "Der Moment eines jungen Anglers" },
      rigTogether: { alt: "Dimitris hilft bei der Vorbereitung der Angelmontage", caption: "Gemeinsam die Montage vorbereiten" },
      barbecue: { alt: "Freunde beim Grillessen an Bord mit geschützten Gesichtern", caption: "Mittagessen an der Ägäis" },
      groupCatch: { alt: "Eine Gruppe beim Tagesfang, Kindergesichter sind geschützt", caption: "Ein gemeinsamer Fang im Hafen" },
      largeCatch: { alt: "Ein junger Gast mit einem großen Fisch und geschütztem Gesicht", caption: "Ein unvergesslicher großer Fang" },
      mealAboard: { alt: "Eine Mahlzeit an Bord mit geschützten Gesichtern", caption: "Eine Mahlzeit an Bord" },
      womanFishing: { alt: "Ein weiblicher erwachsener Gast hält eine Angelrute an Bord, das Gesicht ist geschützt", caption: "Angeln entlang der Küste" },
      dimitrisFish: { alt: "Dimitris hält einen großen Fisch an Bord", caption: "Dimitris und ein großer Fisch" },
      trophy: { alt: "Dimitris präsentiert einen Trophäenfisch", caption: "Ein Trophäenfang mit Dimitris" },
      soup: { alt: "Frische Fischsuppe wird in einem Topf an Bord gekocht", caption: "Frische Fischsuppe an Bord" },
      dimitrisBonito: { alt: "Dimitris hält einen Bonito, der auf Kunstköder gefangen wurde, die Rute noch in der Hand", caption: "Dimitris mit einem Bonito" },
      crewBonito: { alt: "Ein Crewmitglied hält einen Bonito unter dem Sonnendach des Bootes hoch", caption: "Ein Bonito vom Schleppangeln" },
      crewGurnard: { alt: "Dimitris und ein Crewmitglied halten einen Roten Knurrhahn mit ausgebreiteten blauen Flossen", caption: "Roter Knurrhahn mit offenen Flossen" },
      crewOctopus: { alt: "Ein Crewmitglied hält am Kai einen Oktopus, daneben einer der Bordhunde", caption: "Oktopus am Kai" },
      guestPandora: { alt: "Ein Gast hält an Bord eine Rotbrasse, das Gesicht ist geschützt, dahinter Dimitris", caption: "Die Rotbrasse eines Gastes" },
      catchPandora: { alt: "Eine rote Brasse über der Reling, im Hintergrund ein Kind mit geschütztem Gesicht", caption: "Eine rote Brasse an der Reling" },
      catchGurnard: { alt: "Ein Roter Knurrhahn auf der Decksmatte mit ausgebreiteter blauer Brustflosse", caption: "Die blaue Flosse des Knurrhahns" },
      catchBucket: { alt: "Ein Eimer mit Blöker, Laxierfisch und einer Brasse, frisch in Meerwasser gehalten", caption: "Der Eimer nach einem Morgen" },
      boatPuppy: { alt: "Ein junger cremefarbener Hund sitzt am blauen Bug des Bootes im Hafen", caption: "Der Jüngste der Crew" },
      dimitrisNight: { alt: "Dimitris hält eine gerade gefangene Rotbrasse während einer Nachtfahrt", caption: "Eine Rotbrasse auf der Nachtfahrt" },
      sonNight: { alt: "Dimitris' Sohn hält eine nachts gefangene Rotbrasse", caption: "Der Fang seines Sohnes nach Einbruch der Dunkelheit" },
      familySwim: { alt: "Victoria und ihr Sohn ruhen bei einem Badestopp auf den Felsen", caption: "Ein Badestopp an der Küste" },
      barbecuePlatter: { alt: "Eine Platte mit gegrillten Garnelen, gebratenem Fisch und griechischem Salat an Bord", caption: "Das Barbecue an Bord" },
      kelyfosCoast: { alt: "Die Felsküste der Insel Kelyfos vom Wasser aus gesehen", caption: "Die Insel Kelyfos" },
      coveSwimmers: { alt: "Zwei Schwimmer im klaren Wasser einer stillen Bucht unter den Felsen", caption: "Schwimmen in einer stillen Bucht" },
      deckAfternoon: { alt: "Gäste ruhen zwischen den Stopps auf dem schattigen Deck, Gesichter geschützt", caption: "Der Nachmittag an Deck" },
      coveWide: { alt: "Weiter Blick auf die Bucht mit Schwimmern und dem pinienbewachsenen Felsen", caption: "Die Bucht vom Boot aus" },
      kelyfosTurquoise: { alt: "Klares türkisfarbenes Wasser über Felsen an den Klippen von Kelyfos", caption: "Türkisfarbenes Wasser bei Kelyfos" },
      guestFamilyRods: { alt: "Eine Familie angelt bei Sonnenuntergang an der Reling, Gesichter geschützt", caption: "Eine Familie an der Reling" },
      guestsEveningRods: { alt: "Gäste angeln im Abendlicht mit der Küste im Hintergrund, Gesichter geschützt", caption: "Abendliche Schnüre im Wasser" },
    },
  },
};
